apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: busybox-container
      image: busybox
