apiVersion: v1
kind: Pod
metadata:
  name: ngin-02
  labels:
    app: myapp
    tier: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: busybox-container
      image: busybox
